### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/TailwindTraders-Website#124]
The current code on `master` doesn't build with regular web app workflow for GitHub: https://github.com/microsoft/TailwindTraders-Website/runs/559304897?check_suite_focus=true

**Comment by borjasanes** [comment]
Thanks @sdebruyn, you can see the fixed workflow [here](https://github.com/microsoft/TailwindTraders-Website/actions/runs/539639470).
Clossing the issue!
