### ISSUE TITLE
Bad certificates, unsecure connection

### ISSUE THREAD

**Issue by kartikPatidar** [microsoft/TailwindTraders-Website#272]
When opening the site my browser shows the following warning : 
your connection to side is not secure. 
here's a screen shot : 
![Screenshot (4)](https://user-images.githubusercontent.com/44874954/156138454-d6c6ff2a-379a-47c7-9d94-9418670b08b7.png)

**Comment by olgamarti** [comment]
Thanks for reporting the issue. We updated the certificate and the issues is resolved. Thanks!
