### ISSUE TITLE
Deploy doesn't work as image cannot be found

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#3]
Looks like`tailwindtraders/web:latest` hasn't been pushed to Dockerhub which makes the deploy button not work. Code is here:
https://github.com/Microsoft/TailwindTraders-Website/blob/master/Deploy/deployment.json#L21

Fixing it likely means a push to docker hub.

**Comment by dasanagu** [comment]
Thank you for reporting this issue. Fixed with commit [61ff09](https://github.com/Microsoft/TailwindTraders-Website/commit/61ff0974e73df985864b5eada19234885a52146c)
