### ISSUE TITLE
README mentions use of a non-refererenced environment variable `REPOSITORY`

### ISSUE THREAD

**Issue by toolboc** [microsoft/TailwindTraders-Website#34]
In the ["Build and Push the docker image"](https://github.com/microsoft/TailwindTraders-Website#build-and-push-the-docker-image) section of the README, it mentions setting the following environment variable:
> REPOSITORY: Must be the login server of the ACR where Backend is installed.

However, the intended docker-compose file does not use a variable named `REPOSITORY` it instead uses one named `REGISTRY` 

See: https://github.com/microsoft/TailwindTraders-Website/blob/master/Source/docker-compose.yml

Suggestion is to consolidate to one of these names and update the documentation accordingly

**Comment by cdemiguel** [comment]
Hello!,
this is fixed with the las PR, we change in documentation REPOSITORY name to REGISTRY,
https://github.com/microsoft/TailwindTraders-Website/pull/38/commits/4ed5eecadc8e6a7c605c69ff187c8ca7f4a43efc
Thank you!
Regards,
