### ISSUE TITLE
Added a specific ports setting to docker-compose

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#5]
Right now the `docker-compose.yml` file doesn't have any setting for `ports` which means, by default, the site will run on port 80. This doesn't work very well for many dev environments.

I would suggest setting the `ports` specifically, and instructing people in the README to set `ports: 3000:80` so the site works as intended.

**Comment by eiximenis** [comment]
Hi @robconery 

Currently `ports` section is defined in `docker-compose.override.yml` file:

```
    ports:
      - "5100:80"
```

Using `docker-compose up` website listens on `localhost:5100`. Is this enough or I am missing something?

**Comment by robconery** [comment]
Ah - was only looking in the `docker-compose.yml` file. You might consider putting it in there for discoverability, but closing this now.
