### ISSUE TITLE
documentation or guidence on connecting backend

### ISSUE THREAD

**Issue by scautomation** [microsoft/TailwindTraders-Website#50]
When deploying the web portion the readme says:

When you deploy this website to Azure you can define the Backend you want to use in case you have deploy your own backend. By defaults it is configured the public Backend environment provided by Microsoft.

Im having an issue finding documentation or guidance on how exactly you connect the website to the backend. I have both successfully deployed just need specifics on how to connect them.

**Comment by OriolBonjoch** [comment]
Hi @scautomation 

I updated the documentation and fixed the default values to production backend DNS. Documentation changes are at pull request #53.
