### ISSUE TITLE
Hard-coded email setting means app has precisely one user

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#6]
If I understand correctly, this is the client for the server backend, which is (functionally) the shopping cart. Unfortunately the setting below:

https://github.com/Microsoft/TailwindTraders-Website/blob/97ee364e063e16acce35d5bf48bff341812cc57d/Deploy/deployment.json#L34

Hard-codes the client's email address _on the server_, which means that a single deployment has only one possible user. This goes against the idea of a shopping cart, which should allow for multiple users.

**Comment by dasanagu** [comment]
Thanks @robconery. On January we will be updating the fake auth method for B2C. Assigning @eiximenis to this issue.

**Comment by robconery** [comment]
Hi David - if I'm reading the source correctly it looks like the email is still being set within the configuration and that this app can only support a single user? Is this intended?
