### ISSUE TITLE
Is Cosmos DB required for a client app?

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#7]
The setting below will deploy Cosmos DB for the customer when they deploy this application:

https://github.com/Microsoft/TailwindTraders-Website/blob/97ee364e063e16acce35d5bf48bff341812cc57d/Deploy/deployment.json#L44

Given that this is the _client_ application built with React, Cosmos DB is not required (unless I misunderstand something). This can result in customers receving unwanted charges.

**Comment by dasanagu** [comment]
We had a CosmosDB for the coupon functionality but this was moved to the backend so it is not longer necessary. Fix it with commit [b06822](https://github.com/Microsoft/TailwindTraders-Website/commit/b06822fa64b5ed5220eff132b2d8c8d16d3e9156)
