### ISSUE TITLE
.env files should not be checked in

### ISSUE THREAD

**Issue by robconery** [Microsoft/TailwindTraders-Website#8]
One of the primary uses of `.env` files is to use Environment variables instead of hard-coding things. Checking in these files defeats the purpose. I would recommend adding instructions to the README which tells the user how to set environment variables and/or to create a `.env` file.

https://github.com/Microsoft/TailwindTraders-Website/blob/97ee364e063e16acce35d5bf48bff341812cc57d/Source/.env#L10

**Comment by dasanagu** [comment]
Thanks @robconery we will be updating this to replace the hard-coding configuration. Assigning @eiximenis to this issue.
