### ISSUE TITLE
Error when try to use the Standalone "automatic deployment"

### ISSUE THREAD

**Issue by taqabubaker** [microsoft/TailwindTraders-Website#91]
I'm getting an error when I try to auto deploy the solution in Standalone mode. I'm getting **The specified app service plan was not found.** error. Here is the complete error for you to trace.
`{
  "telemetryId": "b3545cfb-b90a-49f9-9477-5e85dce6d6f1",
  "bladeInstanceId": "Blade_ea0851e6347d49e3bb5bd70df9efbe47_0_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '20572e19-7e91-40a1-96e1-85e527ee214b'. See inner errors for details.",
  "details": [
    {
      "code": "ValidationForResourceFailed",
      "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information.",
      "details": [
        {
          "code": "ServerFarmNotFound",
          "message": "The specified app service plan was not found."
        }
      ]
    }
  ]
}`

**Comment by devigned** [comment]
I think this is resolved via #93

**Comment by olgamarti** [comment]
@taqabubaker issue should be fixed, today I merged the fix on PR #93. Please re-open the issue if not. Thanks!

**Comment by taqabubaker** [comment]
Thanks @olgamarti.
I confirm the issue is fixed.
